
logging.level.root=INFO
#spring.data.mongodb.database=shopping_db
#spring.data.mongodb.port=27017


#================================================
# General Properties
#================================================
#server.servlet.contextPath=
server.port=8081
#springdoc.swagger-ui.path=/swagger-ui.html

#================================================
# Database Configurations
#================================================
#spring.data.mongodb.uri=mongodb://admin:admin@localhost:27018/mygrocerylist

spring.data.mongodb.uri=mongodb://localhost:27017/userDatabase
#================================================
# Actuator Configurations
#================================================
#management.endpoint.health.group.custom.show-components=always
#management.endpoint.health.group.custom.show-details=always

#================================================
# Prometheus Configurations
#================================================
#management.endpoints.web.exposure.include=prometheus